# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: ^\.git/.*$
    -   id: end-of-file-fixer
        exclude: ^\.git/.*$
    -   id: check-yaml
        args:
        - --allow-multiple-documents
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-aws-credentials
    -   id: detect-private-key

-    repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
     rev: v5.0.0
     hooks:
     -   id: commitlint
         stages: [commit-msg]

-   repo: local
    hooks:
    -   id: autopep8
        name: autopep8
        entry: autopep8 -i -j 2 --max-line-length=120
        language: system
        types: [ python ]
